### ISSUE TITLE
flatpak runtime end of life

### ISSUE THREAD

**Issue by Jarm3r** [dail8859/NotepadNext#550] opened 2024-04-22 16:18 UTC
Today upon attempting a flatpak update, I got the following message:

`Info: runtime org.kde.Platform branch 6.5 is end-of-life, with reason:
We strongly recommend moving to the latest stable version of the Platform and SDK`

Could this please be updated to the newer platform runtime?

**Comment by dail8859** [comment] 2024-04-22 16:21
@zocker-160 Thoughts?

**Comment by zocker-160** [comment] 2024-04-22 17:40
6.5 has been marked as EOL yesterday:
https://invent.kde.org/packaging/flatpak-kde-runtime/-/commit/fc23bc54ae22f5e17dbef556b37d842cfd7522d8

Not sure what the rationale behind this is, I will investigate.

**Comment by dail8859** [comment] 2024-04-22 18:23
@zocker-160 

> LTS versions of Qt 6.x are not open source

I personally hate this decision (and a few others) by Qt...but I'll not let that derail this issue :)

--- 

Ignoring 5.15 for the moment...what are the KDE expecting application developers to do? Switch to a newer runtime every 6 months (or year if you skip releases)?

Other than the blatant warning, is there any risk ignoring it and sticking with 6.5 anyways?

**Comment by zocker-160** [comment] 2024-04-22 18:38
@dail8859 given that a new Qt 6.x version releases around every 10 - 12 month, it would indeed mean updating once a year.
That being said, I don't think KDE devs like that either nor really have a choice unless they also maintain a second LTS additionally to 5.15.

> Other than the blatant warning, is there any risk ignoring it and sticking with 6.5 anyways?

It is the same risk as running that version on Windows (as you also don't get LTS versions there unless you pay) except that Windows users will never get notified about it :laughing: .

**Comment by Jarm3r** [comment] 2024-04-22 19:01
my only thought as an end-user (and lover of this app!) is that the error message is confusing, and makes it seem like the app itself has something wrong with it. When in reality there's nothing wrong, but I don't think you yourself have any control over the message itself correct?

I've been on linux for years, and this is the first time I've ever seen this error. I had to search to figure out what it meant.

**Comment by dail8859** [comment] 2024-04-22 19:28
Agreed it is very undesirable for the end user. Upgrading to Qt6.6+ is a definitely no-go currently due to 3rd party libraries having issues. Unless @zocker-160 has any magical insight, I think this is going to have to be something we live with for the time being.

**Comment by zocker-160** [comment] 2024-04-22 20:41
> As long as things won't break (e.g. the application won't run) for the flatpak

That risk is very low, I am also maintaining an (abandoned) Application as Flatpak that uses some very old Qt 5.1 and it still works just fine.

This is essentially a layer 8 problem of users feelings.

@Jarm3r 
> When in reality there's nothing wrong, but I don't think you yourself have any control over the message itself correct?

The message is defined in the KDE runtime here:
https://invent.kde.org/packaging/flatpak-kde-runtime/-/blob/qt6.5/flathub.json?ref_type=heads#L4

> Unless @zocker-160 has any magical insight, I think this is going to have to be something we live with for the time being. :(

@dail8859 I know this is additional work for you, but do you have a scenario where I could try to replicate any issue you might know about with 6.6?

On the Flathub beta I did try 6.6 once and it "seemed" to be working, but I did not check any specific functionality.

**Comment by dail8859** [comment] 2024-04-22 21:06
@zocker-160

Specifically https://github.com/itay-grudev/SingleApplication/issues/190#issuecomment-1950231485

Starting multiple instances seem to have issues which the author is aware of. I haven't looked into it in depth myself or tried to replicate it, but the discussion definitely seems to indicate an identified issue.

**Comment by zocker-160** [comment] 2024-04-23 12:36
Yep I can confirm with Qt 6.6 the SingleApplication does indeed not work and a secondary instance is launched instead.

**Comment by dail8859** [comment] 2024-04-23 16:48
@zocker-160 Appreciate all the help and testing!

@Jarm3r Thanks for bringing this to our attention. Unfortunately it will just have to be something we live with for the time being.

**Closed by dail8859** 2024-04-23 16:48 UTC
Labels: linux
