### ISSUE TITLE
optimizing the find and replace text box

### ISSUE THREAD

**Issue by tangkeplus** [dail8859/NotepadNext#216] opened 2022-09-30 08:27 UTC
in Mac
The find and replace text field is too short
If the text is longer, there is too little visible text

**Comment by dail8859** [comment] 2022-09-30 11:07
I do not have a Mac.

Can you post a screenshot of the issue?

**Comment by PaddyTB** [comment] 2022-09-30 11:29
Here you go, from my Mac:  Paddy From: tangkeplus ***@***.***>Date: Friday, 30 September 2022 at 09:27To: dail8859/NotepadNext ***@***.***>Cc: Subscribed ***@***.***>Subject: [dail8859/NotepadNext] optimizing the find and replace text box (Issue #216)in MacThe find and replace text field is too shortIf the text is longer, there is too little visible text—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

**Comment by elcuco** [comment] 2022-11-24 16:12
Can you check if this build fixes the issue for you?
https://github.com/dail8859/NotepadNext/suites/9491423888/artifacts/450040615

**Comment by elcuco** [comment] 2022-11-30 20:17
ping... can you test this version and see if the problem is fixed?

**Comment by dail8859** [comment] 2022-12-29 13:09
@elcuco

Since nobody can verify the fix, what are your thoughts? If you feel it will either fix this issue or at least won't have a negative impact, then I'm fine merging it. If you are bit unsure then maybe we are better off closing this issue along with the PR. I'm fine either way.

**Comment by elcuco** [comment] 2022-12-29 20:27
I asked a friend with a Mac to test the latest artifact from the git, (https://github.com/dail8859/NotepadNext/suites/10093757647/artifacts/491972251), he claims it works fine for him. IMHO, the Qt6 version fixed the issue. Close it.

@tangkeplus please re-open this if after the next update you still see it.

**Comment by dail8859** [comment] 2022-12-29 20:38
@elcuco Thanks!

**Closed by dail8859** 2022-12-29 20:38 UTC
Labels: macos
