### ISSUE TITLE
MacOS Big Sur (11.7.10) can not run NotepadNext APP

### ISSUE THREAD

**Issue by hapjre** [dail8859/NotepadNext#599] opened 2024-07-13 04:19 UTC
### Operating System and Version

MacOS Big Sur ,11.7.10 (20G1427)

### Distribution

pkg,homebrew

### Description

ERROR DETAILS:
![iShot_2024-07-13_12 14 28](https://github.com/user-attachments/assets/71d65c50-271c-4300-a1e0-d8da79405518)

Process:               NotepadNext [87217]
Path:                  /Applications/Notepadnext.app/Contents/MacOS/NotepadNext
Identifier:            io.github.dail8859.NotepadNext
Version:               0.8.0 (0)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           NotepadNext [87217]
User ID:               501

Date/Time:             2024-07-13 12:00:51.373 +0800
OS Version:            macOS 11.7.10 (20G1427)
Report Version:        12
Anonymous UUID:        232F9268-2A6C-29F9-FB45-7983B6B20507

Sleep/Wake UUID:       D58445AB-08D8-47F9-A116-B383C4A56AA8

Time Awake Since Boot: 330000 seconds
Time Since Wake:       400 seconds

System Integrity Protection: disabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x00000000007f6000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Segmentation fault: 11
Termination Reason:    Namespace SIGNAL, Code 0xb
Terminating Process:   exc handler [87217]

VM Regions Near 0x7f6000:
--> 
    __TEXT                      1007f6000-100c86000    [ 4672K] r-x/r-x SM=COW  /Applications/Notepadnext.app/Contents/MacOS/NotepadNext

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   io.github.dail8859.NotepadNext	0x0000000100a6155c NotepadNextApplication::init() + 1404
1   io.github.dail8859.NotepadNext	0x0000000100ad02d8 main + 1928
2   libdyld.dylib                 	0x00007fff2045cf3d start + 1

### Steps to Reproduce

Model: MacBookPro11,1, BootROM 153.0.0.0.0, 2 processors, Dual-Core Intel Core i5, 2.6 GHz, 8 GB, SMC 2.16f68
Graphics: kHW_IntelIrisItem, Intel Iris, spdisplays_builtin
Memory Module: BANK 0/DIMM0, 4 GB, DDR3, 1600 MHz, 0x80AD, 0x484D54343531533641465238412D50422020
Memory Module: BANK 1/DIMM0, 4 GB, DDR3, 1600 MHz, 0x80AD, 0x484D54343531533641465238412D50422020
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0x112), Broadcom BCM43xx 1.0 (7.77.111.1 AirPortDriverBrcmNIC-1680.11)
Bluetooth: Version 8.0.5d7, 3 services, 27 devices, 1 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
USB Device: USB 3.0 Bus
USB Device: Ultra Fit
USB Device: Apple Internal Keyboard / Trackpad
USB Device: BRCM20702 Hub
USB Device: Bluetooth USB Host Controller
Thunderbolt Bus: MacBook Pro, Apple Inc., 17.2

### Additional Details

e.g. screenshots, logs, etc

**Comment by hapjre** [comment] 2024-07-13 04:20
[error.txt](https://github.com/user-attachments/files/16200891/error.txt)
![iShot_2024-07-13_12 14 28](https://github.com/user-attachments/assets/c6a9cb02-7d14-4c96-99d3-05753b6b4f2a)

**Comment by dail8859** [comment] 2024-07-13 21:39
I don't use Mac at all so hopefully someone else can help troubleshoot.

**Comment by bsdooby** [comment] 2024-10-17 21:22
Qt version not supported (Qt 6 vs Qt 5 [GitHub does no longer provde Qt 5 builds])?

**Comment by dail8859** [comment] 2024-10-19 13:28
> GitHub does no longer provde Qt 5 builds

Qt5 builds started failing for the GitHub actions on MacOS, so that was removed since I do not have a mac to test/debug what the problem is. If someone wants to add this back in that's fine with me even though Qt5 is not _officially_ supported, I don't mind keeping it around for a while.

> Qt version not supported 

This shouldn't be an issue with Qt. Both [Qt 6.5](https://doc.qt.io/qt-6.5/supported-platforms.html#macos) and[ Qt 5.15](https://doc.qt.io/qt-5/supported-platforms.html#macos) support macOS 11

**Comment by dail8859** [comment] 2024-12-19 18:49
Closing for now since nobody else has reported this and there's not much I can do. The only thing that may be the cause is possibly it being built by a newer version of xcode maybe, but I won't be able to support custom builds of the application for MacOS.

**Closed by dail8859** 2024-12-19 18:49 UTC
Labels: macos
