### ISSUE TITLE
could it support the style of darkness

### ISSUE THREAD

**Issue by omyhub** [dail8859/NotepadNext#488] opened 2023-11-29 03:15 UTC
white make eyes tired quickly ,  darkness make me focus on the importance ,  i hope it would support the darkness mode .

**Comment by dail8859** [comment] 2023-11-29 12:51
Duplicate of https://github.com/dail8859/NotepadNext/issues/407, an initial PR has been submitted but I haven't had a chance to look at it much https://github.com/dail8859/NotepadNext/pull/411

**Closed by dail8859** 2023-11-29 12:51 UTC
