### ISSUE TITLE
Multi-language does not support Chinese, can we add Chinese? Thanks to the author!

### ISSUE THREAD

**Issue by xiaokentrl** [dail8859/NotepadNext#91] opened 2022-04-12 09:02 UTC
Multi-language does not support Chinese, can we add Chinese? Thanks to the author!

**Comment by dail8859** [comment] 2022-04-12 11:57
Thanks for opening the issue!

Currently the application is not multi-lingual at all. I'd be very interested if someone could work and contribute additional translations for the application, but I won't be able to directly help myself. 

Closing as a duplicate of #56. Best to discuss any additional translation topics there.

**Closed by dail8859** 2022-04-12 11:57 UTC

**Comment by xiaokentrl** [comment] 2022-04-12 12:39
I can provide translation of the translated content, and I hope you can tell me the part that needs to be translated. Because of my limited technical ability, I can only make changes in the places you pointed out.


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "dail8859/NotepadNext"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月12日(星期二) 晚上7:57
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [dail8859/NotepadNext] Multi-language does not support Chinese, can we add Chinese? Thanks to the author! (Issue #91)





 
Thanks for opening the issue!
 
Currently the application is not multi-lingual at all. I'd be very interested if someone could work and contribute additional translations for the application, but I won't be able to directly help myself.
 
Closing as a duplicate of #56. Best to discuss any additional translation topics there.

**Comment by dail8859** [comment] 2022-04-12 13:33
There's a bit of a process involved to get the translation files set up to actually have the translations made. I'm honestly not that sure how the process works exactly. Qt has documentation on this process [here](https://doc.qt.io/qt-5/internationalization.html)
