### ISSUE TITLE
support dark mode and export config and import config function

### ISSUE THREAD

**Issue by newyorkthink** [dail8859/NotepadNext#486] opened 2023-11-27 19:04 UTC

**Comment by dail8859** [comment] 2023-11-28 13:52
> support dark mode

Duplicate of #407, an initial PR has been submitted but I haven't had a chance to look at it much #411

> export config and import config

If you want your config you can grab all the files in `C:\Users\myuser\AppData\Roaming\NotepadNext` not sure what other functionality you had in mind for exporting/importing configs.

**Closed by dail8859** 2023-11-28 13:52 UTC
