### ISSUE TITLE
Ubuntu 22.04.3 LTS 下无法输入中文

### ISSUE THREAD

**Issue by aohanhongzhi** [dail8859/NotepadNext#496] opened 2024-01-10 08:23 UTC
输入法写在别的地方正常，基本上确定不是输入法的问题。

![image](https://github.com/dail8859/NotepadNext/assets/37319319/71afe7f6-4e66-49c8-8e41-b4ce7d827e70)

**Comment by dail8859** [comment] 2024-01-19 12:29
@WzLYVg387U There has already been discussion about fcitx support in #218 so I'd recommend any further discussion can be added there.

I don't have a good way to test any of the various input methods, so any help someone could offer would be great.

Closing this as a duplicate of #218

**Closed by dail8859** 2024-01-19 12:29 UTC
Labels: linux
