### ISSUE TITLE
[feature-request] don't ask save when close

### ISSUE THREAD

**Issue by PandaFang** [dail8859/NotepadNext#233] opened 2022-10-15 09:11 UTC
希望关闭时可以不询问保存，开了多个标签 临时处理一下文本，关闭时 对话框实在影响操作流畅性

**Comment by PNBRQK** [comment] 2022-10-15 10:03
yeah, since Notepad++ offers to save temp buffers to a session on exiting without an ask-to-save prompt...

**Comment by dail8859** [comment] 2022-10-16 01:13
Duplicate of #81 and others

**Closed by dail8859** 2022-10-16 01:13 UTC
