### ISSUE TITLE
Unable to use input method  Rime

### ISSUE THREAD

**Issue by erdong01** [dail8859/NotepadNext#640] opened 2024-09-05 03:00 UTC
### Operating System and Version

MacOs 15.0

### Distribution

NotepadNext-v0.8.dmg

### Description

Unable to use input method  Rime
Rime version:1.02

### Steps to Reproduce

1. 
2. 
3. 

### Additional Details

e.g. screenshots, logs, etc

**Comment by dail8859** [comment] 2024-09-05 11:29
Duplicate of #551

**Closed** 2024-09-05 11:30 UTC
Labels: macos
