### ISSUE TITLE
Chinese(中文'在') supports issues

### ISSUE THREAD

**Issue by duanxg** [dail8859/NotepadNext#268] opened 2022-11-14 02:01 UTC
![image](https://user-images.githubusercontent.com/6904919/201559308-8972f6d8-efc1-47eb-bc4d-10828b275893.png)
I found the chinese ('在')  font is different from other font.

**Comment by wylapp** [comment] 2022-11-15 15:57
这个问题似乎跟系统字体有关系，不知道你是Windows哪一个版本。主要的问题还是在于，Notepad Next编辑区默认是英文字体，而且这个字体现在手动改不了。
This problem seems to be related to system font settings, I don't know which version of Windows you are using. The main problem is the editing box uses monospace font , which does not support Chinese characters, in such case will use a fallback font, and both main font and fallback font cannot be changed currently by user.

**Comment by dail8859** [comment] 2022-11-15 16:28
> This problem seems to be related to system font settings

I agree.

> in such case will use a fallback font

I don't believe Scintilla (the actually editing part of the application) supports fallback fonts, but not sure if Qt is doing something as well.

Do you think forcing the font to `Courier New` would fix this? I don't read Chinese but from just copy/pasting text into my setup seems like it is rendered correctly.

![image](https://user-images.githubusercontent.com/3694843/201973217-4e46d80d-7a3c-4cfd-97a2-beabb6b0ec15.png)

**Comment by dail8859** [comment] 2022-11-15 16:36
One other thing to try. Type the 在 character in a file, then open `Help > Lua Console` and type this in the console and run it to see if it changes anything:

```lua
editor.StyleFont[0] = 'Courier New'
```

**Comment by dail8859** [comment] 2022-12-18 02:40
Anyone able to test the suggestion above that is encountering this?

**Comment by inkydragon** [comment] 2022-12-18 04:13
I can't reproduce this issue.

09c5069 NotepadNext-Windows-Qt6.4.1-Zip

![微信图片_20221218115136](https://user-images.githubusercontent.com/5158738/208280611-b7e7f9f5-8ec6-4d82-8979-e155e4f29818.png)
![微信图片_20221218115148](https://user-images.githubusercontent.com/5158738/208280609-0bda3d9c-9094-46d0-89f3-78eeb10366a0.png)

**Comment by inkydragon** [comment] 2022-12-18 04:17
When win 10 uses the Simplified Chinese language pack, the default font should be "Microsoft YaHei (UI)".

"MS YaHei" is a sans-serif font, sometimes the font will fallback to the serif font "Sim Sun".


`请打开手机微信扫一扫功能`

- "Microsoft YaHei", cn name: "微软 雅黑", sans-serif
![image](https://user-images.githubusercontent.com/5158738/208280973-ea00f173-e726-49d7-9894-16ac1a5f06b6.png)

- "Sim Sun", cn name: "宋体", serif
![image](https://user-images.githubusercontent.com/5158738/208280950-92462c68-62f1-4618-a73a-06e63ae128fd.png)


My guess is that the font used in the picture is not a (Simplified) Chinese font, it may be a Traditional Chinese font, Japanese font or Korean font, or it may be another font and then fallback to a non-Simplified Chinese font.

The reason for this guess is that the character "信" in the image is not written in the standard Simplified Chinese style.


![1671336405445](https://user-images.githubusercontent.com/5158738/208280779-014354bc-7348-4b38-a12b-e1b244f5fb6c.png)
—— https://www.likefont.com/community/82570649/identify/

**Comment by inkydragon** [comment] 2022-12-18 04:56
> but not sure if Qt is doing something as well.

QT does have a list of fallback fonts:
https://github.com/qt/qtbase/blob/5a0dcda171772e75eeb22f719cec36ef8efe355d/src/gui/text/windows/qwindowsfontdatabasebase.cpp#L831-L839
```cpp
static const char *ch_CN_tryFonts [] = {
    "SimSun",
    "Arial",
    "PMingLiU",
    "Gulim",
    "MS UI Gothic",
    "Arial Unicode MS",
    0
};
```

**Comment by dail8859** [comment] 2022-12-18 14:46
@inkydragon thanks for the excellent info as always. 

So it seems this is a user configuration issue rather than something Notepad Next needs to account for?

**Comment by inkydragon** [comment] 2022-12-19 12:38
> So it seems this is a user configuration issue rather than something Notepad Next needs to account for?

I can't reproduce the same issues, so I'm not sure.
I think modifying the system's default font is a possibility workaround.

----

Qt has automatic font fallback, I don't know if we can set it manually.
But at least we can set a font that has good support for both Chinese and English.

**Comment by wylapp** [comment] 2022-12-25 16:57
I believe we have missed some details. Here’s a comparison of exact same text between windows notepad and Notepad Next. I’ve changed windows notepad font settings to ‘Courier New’. These alphabets seem all the same. But these Chinese Characters have the difference, in windows notepad, they are much wider.
![image](https://user-images.githubusercontent.com/11030493/209475529-46752d31-ace4-46ad-bc8b-8e72bee626a7.png)

> I don't think "Courier New" contains any Chinese characters, the Chinese font here seems to be using the system's fallback font.

The truth is: these Chinese characters in Notepad Next use SimSun, which is JUST the first fall back font in QT. Courier New 'contains' Chinese font, using font linking method.

> When win 10 uses the Simplified Chinese language pack, the default font should be "Microsoft YaHei (UI)".
> "MS YaHei" is a sans-serif font, sometimes the font will fallback to the serif font "Sim Sun".

And about "MS YaHei", nowadays windows do use such font as default, but SimSun is still preserved as secondary fallback. This has a history reason because SimSun included in windows has a special optimization for low-res screens, which makes intricate Chinese characters still readable.

> ![image](https://user-images.githubusercontent.com/6904919/201559308-8972f6d8-efc1-47eb-bc4d-10828b275893.png) I found the chinese ('在') font is different from other font.

Back to the original issue, I support the view that [duanxg](https://github.com/duanxg) does not have a proper simplified chinese environment (user configuration issue). In his screenshot the not normal character is '开'(open) not '在'(at), there's even no '在' in the whole sentence, thus I guess he is not a Chinese user, also not using a Chinese version Windows.

SimSun is basically national standard font for Chinese, if user's Windows does not have one, we really have noting to help.

**Comment by dail8859** [comment] 2022-12-29 03:41
@wylapp Awesome info! I'm strictly an English user so pretty much of the intricacies for non-English languages/fonts/etc are quite mysterious to me. But I do understand Windows does alot of magic behind the scenes with font linking, fallback fonts, etc.

There's been discussion with Notepad++ around these same issues. Plus with Notepad Next, there is Qt to consider (which seems to have some type of font fallback support as @inkydragon pointed out).

> does not have a proper simplified chinese environment (user configuration issue)

For now I'm tending to agree with this conclusion. I'll close this issue for now. If more users start encountering this and someone can determine a good solution then I'd be willing to consider it.

**Closed by dail8859** 2022-12-29 03:41 UTC
