### ISSUE TITLE
feature: Auto save & load unnamed documents

### ISSUE THREAD

**Issue by chen3feng** [dail8859/NotepadNext#178] opened 2022-07-22 00:32 UTC
Just like notepad++ doing, so we can use it as a very handy scribbling pad.

thanks.

**Comment by PaddyTB** [comment] 2022-07-22 07:36
+1

Thanks for all the work on NoteNext BTW!

On 22 Jul 2022, at 02:33, CHEN Feng ***@***.***> wrote:

﻿
Just like notepad++ doing, so we can use it as a very handy scribbling pad.

thanks.

**Comment by dail8859** [comment] 2022-07-22 11:32
Duplicate of #81

There's a little bit more discussion on that issue. In short the functionality is definitely desirable to have in the application at some point. There's just currently quite a bit of missing functionality that needs implemented before this would be feasible.

**Closed by dail8859** 2022-07-22 11:32 UTC
