### ISSUE TITLE
Add reopen buffer which close the last session

### ISSUE THREAD

**Issue by yqynju** [dail8859/NotepadNext#243] opened 2022-10-24 01:59 UTC
it cannot reopen all buffer which opened in last session.

**Comment by dail8859** [comment] 2022-10-24 11:52
See #81 

Duplicate of https://github.com/dail8859/NotepadNext/issues/96, #178, #233 https://github.com/dail8859/NotepadNext/issues/236, #237

**Closed by dail8859** 2022-10-24 11:52 UTC
