### ISSUE TITLE
Unusable diaglog boc for find/replace

### ISSUE THREAD

**Issue by doobes** [dail8859/NotepadNext#586] opened 2024-07-02 12:32 UTC
### Operating System and Version

Zorin 

### Distribution

Flathub

### Description

When using the search/replace function, the window is squeezed vertically making test entry impossible.

See screen grab

Note: This problem is not exhibited in the AppImage format.

### Steps to Reproduce

1. Upon NotePad Next
2. Select Search->Replace
3. 
4. 

### Additional Details

![image](https://github.com/dail8859/NotepadNext/assets/23409761/10537d73-bac2-42c7-ac72-ed84876a4bc5)

**Comment by dail8859** [comment] 2024-07-02 13:56
Closing as a duplicate of #348

> Note: This problem is not exhibited in the AppImage format.

Im not overly familiar with Linux but I believe the AppImage doesn't follow any theming support that is enabled for Qt/KDE so that's why the AppImage behaves differently.

**Closed by dail8859** 2024-07-02 13:56 UTC
Labels: linux
