### ISSUE TITLE
Native support for ARM-Based Macs

### ISSUE THREAD

**Issue by GithubGey** [dail8859/NotepadNext#199] opened 2022-09-19 13:35 UTC
期待可以出一个mac M1版本的

**Comment by dail8859** [comment] 2022-09-19 13:51
If the currently available .dmg file on the releases page does not run on mac M1 then I'm not able to do much. I don't use Mac at all so I'm not sure what all this would require. Someone else would have to look into it.

**Comment by gtn1024** [comment] 2022-10-09 02:49
QT's native support for Apple Silicon is from [QT 6.2](https://www.qt.io/blog/qt-on-apple-silicon)

**Comment by necokeine** [comment] 2022-10-09 09:31
Maybe I can take this issue, I have a mac and did some Qt development several years ago.

**Comment by necokeine** [comment] 2022-10-09 11:17
I'm not sure whether this dmg works too on your side.
https://github.com/necokeine/NotepadNext/releases/tag/v0.5.5

**Comment by dail8859** [comment] 2022-10-09 12:25
@necokeine 

> Maybe I can take this issue

Any help would be greatly appreciated! And if it's only possible with Qt6.2 then that's fine. This project will be moving to that at some point in the near future.

**Comment by xiaoduo** [comment] 2022-10-12 05:33
I'm using M1 Macbook pro, just tried the .dmg in release 0.55, it can work.

**Comment by PaddyTB** [comment] 2022-10-12 08:42
I’m using a Mac M1 too and the 0.5.5 dmg works fine

**Comment by 72min** [comment] 2022-10-12 09:05
> If the currently available .dmg file on the releases page does not run on mac M1 then I'm not able to do much. I don't use Mac at all so I'm not sure what all this would require. Someone else would have to look into it.

估计他的意思是 希望支持 M1的arm架构  目前是可以通过转译运行。

**Comment by PaddyTB** [comment] 2022-10-12 09:09
Yes, it's running the Intel binaries just fine under Rosetta

**Comment by dail8859** [comment] 2022-10-12 15:55
Forgive me for being completely illiterate when it comes to Mac hardware...so is this still a valid issue? Or are there arm-based M1 chips that this application still doesn't work for?

**Comment by PaddyTB** [comment] 2022-10-12 18:43
Intel binaries get translated at runtime by Rosetta 2 on ARM macs - and this appears to be working fine for me and @xiaoduo. Native ARM support will be cool when it comes along but I believe it’s working well under emulation for now. It’s not a bug / issue so much a a feature request or enhancement IMO as we should (hopefully) get improved performance once it runs natively on ARM. HTH

**Comment by necokeine** [comment] 2022-10-13 05:27
> @necokeine
> 
> > Maybe I can take this issue
> 
> Any help would be greatly appreciated! And if it's only possible with Qt6.2 then that's fine. This project will be moving to that at some point in the near future.

Yes, this compilation is only success Qt higher than 6.2, I did it with Qt6.4. I believe that Qt could cross-compile M1 binary on other platform, so all things should be done is just add a new compilation process for M1.

**Comment by 72min** [comment] 2022-10-18 19:28
> 原谅我在Mac硬件方面完全是文盲...那么这仍然是一个有效的问题吗？或者是否有基于arm的M1芯片，此应用程序仍然不起作用？

转译运行性能跟效率不佳，如果只是简单文本记录影响不大，但是在需要占用大量ram cpu的时候就会表现卡顿。如果可以编译支持arm64架构的应用 会更佳。

**Comment by elcuco** [comment] 2022-10-18 20:24
[https://doc.qt.io/qt-6/macos.html - ](https://doc.qt.io/qt-6/macos.html#architectures) it seems the fix is trivial. Can anyone with a Mac confirm that the generated binary contains also arm64 support?

**Comment by PaddyTB** [comment] 2022-10-18 20:58
> [https://doc.qt.io/qt-6/macos.html - ](https://doc.qt.io/qt-6/macos.html#architectures) it seems the fix is trivial. Can anyone with a Mac confirm that the generated binary contains also arm64 support?

Indeed  and @necokeine has already done it - his his message earlier in this thread... but the underlying QT version needs to be 6.2+

**Comment by elcuco** [comment] 2022-10-21 19:33
@dail8859 You are currently using Qt 6.2.4 for official builds. IMHO, you can bump this to 6.3.1 without issues. This would fix the official releases, no? If someone wants to locally build against 6.1.x or 6.2.x - some things might be broken. (I am using 6.4.x and its fine, but you might be more conservative).

https://github.com/dail8859/NotepadNext/blob/fe75620eecb2a35e59383acfec98a252dc60a636/.github/workflows/build.yml#L23

**Comment by dail8859** [comment] 2022-10-21 19:51
@elcuco I'm building with 6.2.4 in the action (and generating the artifact), but the binaries published on the releases page are still using 5.15. 

In the next release or two I plan to officially switch to 6.2 (or later) for the 'official' binaries.

**Comment by dail8859** [comment] 2022-12-06 13:22
So now that Qt6.2 (and also Qt6.4) is being used, is this issue as simple as adding:

```
QMAKE_APPLE_DEVICE_ARCHS = x86_64 arm64
```

To the project file?

**Comment by dail8859** [comment] 2023-01-06 13:56
I've got a new test build (you'll need to unzip it first). This should be a multi-architecture binary that supports ARM.

https://github.com/dail8859/NotepadNext/suites/10221193752/artifacts/500858023

**Comment by GithubGey** [comment] 2023-01-07 01:48
> I've got a new test build (you'll need to unzip it first). This should be a multi-architecture binary that supports ARM.
> 
> https://github.com/dail8859/NotepadNext/suites/10221193752/artifacts/500858023

收到 我试试

**Comment by dail8859** [comment] 2023-01-11 00:33
@PaddyTB Thanks for the info and testing it out!

**Closed** 2023-01-11 00:35 UTC
Labels: macos
