### ISSUE TITLE
bug report ,thx for Next !

### ISSUE THREAD

**Issue by whizsail** [dail8859/NotepadNext#225] opened 2022-10-10 15:10 UTC
macos 12.6 (21G115)

when using:
chinese  pinyin(mac) : when i click  " shift " and " - ", Next will quit 

<img width="632" alt="image" src="https://user-images.githubusercontent.com/33980241/194898245-3cfd0459-53d1-45ca-b5a0-d5400e824367.png"

**Comment by dail8859** [comment] 2022-10-10 15:17
Possible duplicate of #194?

**Comment by dail8859** [comment] 2022-10-11 12:05
You might also try the Qt6 version of the application to see if it has the same issue: https://github.com/dail8859/NotepadNext/suites/8689367306/artifacts/391921672

**Comment by dail8859** [comment] 2022-10-13 11:43
Closing as a duplicate of #194

If you have any additional details feel free to post on that issue. If what you've ran across is different from that issue then this can be reopened.

**Closed by dail8859** 2022-10-13 11:43 UTC
Labels: macos
