### ISSUE TITLE
would you please support edit code styles by user

### ISSUE THREAD

**Issue by LeeR01** [dail8859/NotepadNext#544] opened 2024-04-09 06:06 UTC
There are a very large number of code styles supported in this app at the moment, but I'm using a niche software within my specialty, and I'd like to be able to edit my own code styles and use them in this app.

**Comment by LeeR01** [comment] 2024-04-11 00:46
Sorry, I haven't used the "notepad++" editor you mentioned. What I was trying to say is that I can highlight code according to the characteristics of the language I am using, similar to what is meant by modifying keywords in the code style file. For example, if I'm using MATLAB (which is already supported, of course), I can change the "for end" in there to be bolded in green.



***@***.***
 
From: dail8859
Date: 2024-04-10 22:31
To: dail8859/NotepadNext
CC: LeeR01; Author
Subject: Re: [dail8859/NotepadNext] would you please support edit code styles by user (Issue #544)
Are you meaning like Notepad++'s Style configurator?

**Comment by dail8859** [comment] 2024-04-11 01:34
Currently it is not possible, but this is planned in the future. Currently all the style information is hard coded.

I'll close this issue as a duplicate of #397 and track any progress there.

**Closed by dail8859** 2024-04-11 01:34 UTC
