### ISSUE TITLE
copy full path failed

### ISSUE THREAD

**Issue by Van-wang** [dail8859/NotepadNext#275] opened 2022-11-21 13:44 UTC
the menu cann't copy full path of file, just copy the top dir.
same as the menu of copy floder path.

**Comment by dail8859** [comment] 2022-11-21 13:50
You'll have to provide more details because it works for me on Windows 10.

What OS are you using and what does the file path look like? Can you open the `Help > Debug Log` and pasted the first 15 lines or so?

**Comment by dail8859** [comment] 2022-11-23 02:49
Works on Ubuntu 22.04 also.

**Comment by dail8859** [comment] 2022-11-26 04:08
Works on Fedora 37 also.

Closing for now. If you have a set of steps to reproduce this or more specific information, please let me know.

**Closed by dail8859** 2022-11-26 04:08 UTC
