### ISSUE TITLE
选定文件右键打开无效

### ISSUE THREAD

**Issue by dickzhenhua** [dail8859/NotepadNext#436] opened 2023-09-06 03:18 UTC
选定文件右键打开无效，多选也一样，无反应。

**Comment by dail8859** [comment] 2023-09-06 12:28
> The selected file is not open with the right click, and the multi-selection is the same, and there is no response.

Can you provide more details? What OS are you using? Is the application already open? An exact set of steps to reproduce the issue would be helpful.

It is working fine for me.

**Comment by dickzhenhua** [comment] 2023-09-06 12:36
> > The selected file is not open with the right click, and the multi-selection is the same, and there is no response.
> 
> Can you provide more details? What OS are you using? Is the application already open? An exact set of steps to reproduce the issue would be helpful.
> 
> It is working fine for me.

使用的是deepin以及UOS，基于debian的发行版。
应用程序不管打开还是没打开，右键就好像毫无作用一般，无法打开选取的文件（无论单个文件还是多个文件）

**Comment by dail8859** [comment] 2023-09-06 12:38
Can you open `Help > Debug Log` and copy/paste the first 10 lines or so from that to see what command line parameters are getting sent to the application on first launch?

**Comment by dickzhenhua** [comment] 2023-09-06 12:50
> Can you open `Help > Debug Log` and copy/paste the first 10 lines or so from that to see what command line parameters are getting sent to the application on first launch?

十分抱歉，我并非程序员，不懂这些操作。不管AppImage还是通过flatpak安装的，都存在这样的问题，我也正是以为系统指定的文本文件默认使用NotepadNext-v0.6.3-x86_64.AppImage打开而出错，所以专门使用flatpak安装使用，结果还是一样，这个问题我在deepin系统的BBS里面发过帖子（因为是论坛里面的网友推荐我使用这个应用程序的），结果他们也是一样，都是右键无法打开文件。

**Comment by dail8859** [comment] 2023-09-06 12:54
I don't use Linux at all so I'm not able to debug it.

I need this information:

![image](https://github.com/dail8859/NotepadNext/assets/3694843/846301c8-234b-46cb-9769-7c244dc0ba0c)

**Comment by dickzhenhua** [comment] 2023-09-06 13:22
> I don't use Linux at all so I'm not able to debug it.
> 
> I need this information:
> 
> ![image](https://user-images.githubusercontent.com/3694843/266013019-846301c8-234b-46cb-9769-7c244dc0ba0c.png)

[     0.064] I: =============================
[     0.064] I: Notepad Next v0.6.3 (Flatpak)
[     0.064] I: Build Date/Time: Jun  2 2023 10:47:03
[     0.064] I: Qt: 5.15.10
[     0.064] I: OS: KDE Flatpak runtime
[     0.064] I: Locale: zh_CN
[     0.064] I: CPU: x86_64
[     0.064] I: File Path: /app/bin/NotepadNext
[     0.064] I: Arguments: NotepadNext
[     0.064] I: =============================
[     0.064] I: bool NotepadNextApplication::init()
[     0.094] I: void NotepadNextApplication::loadTranslation(QLocale)
[     0.094] I: Loaded zh_CN translation :/i18n/NotepadNext_zh_CN.qm for Notepad Next
[     0.094] I: zh_CN translation not found for Qt components
[     0.094] I: LuaState::LuaState()
[     0.112] I: MacroManager::MacroManager(QObject*)
[     0.112] I: void MacroManager::loadSettings()
[     0.112] I: MainWindow::MainWindow(NotepadNextApplication*)
[     0.187] I: setupUi Completed
[     0.219] I: FileListDock::FileListDock(MainWindow*)
[     0.219] I: void MainWindow::setupLanguageMenu()
[     0.242] I: void MainWindow::restoreSettings()
[     0.242] I: void NotepadNextApplication::openFiles(const QStringList&)
[     0.242] I: void MainWindow::newFile()
[     0.242] I: void EditorManager::setupEditor(ScintillaNext*)
[     0.245] I: void MainWindow::addEditor(ScintillaNext*)
[     0.245] I: void MainWindow::detectLanguage(ScintillaNext*)
[     0.245] I: void MainWindow::setLanguage(ScintillaNext*, const QString&)
[     0.245] I: Language Name: Text
[     0.245] I: void DockedEditor::addEditor(ScintillaNext*)
[     0.388] I: void MainWindow::activateEditor(ScintillaNext*)
[     0.389] I: bool MainWindow::checkFileForModification(ScintillaNext*)
[     0.389] I: void MainWindow::updateGui(ScintillaNext*)
[     0.389] I: void MainWindow::updateFileStatusBasedUi(ScintillaNext*)
[     0.389] I: void MainWindow::updateSaveStatusBasedUi(ScintillaNext*)
[     0.390] I: void MainWindow::updateEOLBasedUi(ScintillaNext*)
[     0.390] I: void MainWindow::updateLanguageBasedUi(ScintillaNext*)
[     0.508] I: void MainWindow::focusIn()
[     0.508] I: bool MainWindow::checkFileForModification(ScintillaNext*)
[     0.666] I: Scintilla::Internal::RegexSearchBase* Scintilla::Internal::CreateRegexSearch(CharClassify*)
[    70.597] I: void MainWindow::focusIn()
[    70.598] I: bool MainWindow::checkFileForModification(ScintillaNext*)

**Comment by dail8859** [comment] 2023-09-06 13:30
> [ 0.064] I: File Path: /app/bin/NotepadNext
[ 0.064] I: Arguments: NotepadNext

So this at least indicates it is not an issue with the application since the file paths are not getting passed to the application. Must be with some integration with the OS. Maybe someone else more familiar with Linux can verify or offer some suggestions as to a possible fix.

**Comment by jetsung** [comment] 2023-09-27 09:01
> > [ 0.064] I: File Path: /app/bin/NotepadNext
> > [ 0.064] I: Arguments: NotepadNext
> 
> So this at least indicates it is not an issue with the application since the file paths are not getting passed to the application. Must be with some integration with the OS. Maybe someone else more familiar with Linux can verify or offer some suggestions as to a possible fix.

```bash
[     0.155] I: =============================
[     0.155] I: Notepad Next v0.6.3 (AppImage)
[     0.155] I: Build Date/Time: Jun  2 2023 02:12:55
[     0.155] I: Qt: 6.5.1
[     0.155] I: OS: Deepin 23
[     0.155] I: Locale: zh_CN
[     0.155] I: CPU: x86_64
[     0.155] I: File Path: /tmp/.mount_NotepaFl7qkZ/usr/bin/NotepadNext
[     0.155] I: Arguments: /tmp/.mount_NotepaFl7qkZ/AppRun.wrapped file:///home/jetsung/Downloads/helloworld.txt
[     0.155] I: =============================
[     0.155] I: bool NotepadNextApplication::init()
[     0.181] I: void NotepadNextApplication::loadTranslation(QLocale)
[     0.184] I: Loaded zh_CN translation :/i18n/NotepadNext_zh_CN.qm for Notepad Next
[     0.184] I: zh_CN translation not found for Qt components
[     0.184] I: LuaState::LuaState()
[     0.217] I: MacroManager::MacroManager(QObject*)
[     0.217] I: void MacroManager::loadSettings()
[     0.217] I: MainWindow::MainWindow(NotepadNextApplication*)
[     0.269] I: setupUi Completed
[     0.339] I: FileListDock::FileListDock(MainWindow*)
[     0.339] I: void MainWindow::setupLanguageMenu()
[     0.360] I: void MainWindow::restoreSettings()
[     0.360] I: void NotepadNextApplication::openFiles(const QStringList&)
[     0.360] I: void MainWindow::openFileList(const QStringList&)
[     0.360] I: file:///home/jetsung/Downloads/helloworld.txt
[     3.209] I: void MainWindow::newFile()
[     3.210] I: void EditorManager::setupEditor(ScintillaNext*)
```

It seems that the received path has not been repaired.

**Comment by dail8859** [comment] 2023-09-27 11:37
> `[     0.155] I: Arguments: /tmp/.mount_NotepaFl7qkZ/AppRun.wrapped file:///home/jetsung/Downloads/helloworld.txt`

@jetsung Ah! That's the culprit!

Thanks for the code snippet! I think that is the right solution. Feel free to create a PR or I can easily make the code modifications as well once I have some time. Just want to do a little bit of testing on Windows to make sure there's no negative impact.

**Comment by dail8859** [comment] 2023-09-28 02:48
Closing issue for now since there doesn't appear to be anything that can be done for the original issue unless someone can provide more details/suggestions.

Will be pushing the patch provided by @jetsung momentarily.

**Closed by dail8859** 2023-09-28 02:48 UTC
Labels: linux
