### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by JakobDev** [dail8859/NotepadNext#105] opened 2022-04-19 10:56 UTC
Would be nice, if you could add the possibility to translate the program

**Comment by dail8859** [comment] 2022-04-19 11:06
Thanks for opening this issue. This is currently in development in #103

I'll close this as a duplicate of #56. That issue was specifically for Chinese, but once the translation system is working for one language then it is pretty straight forward to add additional languages. Once there is support for translations, then any help adding new translations would be appreciated.

**Closed by dail8859** 2022-04-19 11:06 UTC
