### ISSUE TITLE
Crach when creating a new file from the terminal when notepadNext is already open

### ISSUE THREAD

**Issue by HeWhoThreadsLightly** [dail8859/NotepadNext#276] opened 2022-11-21 20:45 UTC
### Bug report
NotepadNext craches if you try to create a new file from the terminal when notepad next is already open.
Crach occurs after you click yes or no in the create new file dialog.

### Platform
Steamdeck, steamos stable, flatpack, NotepadNext

### Steps to reproduce
1. Open notepad next in a existing or new file.
2. Open notepad next in a new file from the terminal.
3. Click yes/no/close in the create new file dialog
4. Crach!

    `(deck@steamdeck bin)$ flatpak run com.github.dail8859.NotepadNext test &`
    `(deck@steamdeck bin)$ flatpak run com.github.dail8859.NotepadNext test2 &`

### Full output
    (deck@steamdeck bin)$ flatpak run com.github.dail8859.NotepadNext test &
    [1] 15456
    (deck@steamdeck bin)$
    [     1.185] W: Qt: Session management error: Could not open network socket
    [     1.223] I: =============================
    [     1.223] I: Notepad Next v0.5.4 (Flatpak)
    [     1.223] I: Build Date/Time: Sep 11 2022 17:51:29
    [     1.223] I: Qt: 5.15.7
    [     1.223] I: OS: KDE Flatpak runtime
    [     1.223] I: Locale: en_US
    [     1.223] I: CPU: x86_64
    [     1.223] I: File Path: /app/bin/NotepadNext
    [     1.223] I: Arguments: NotepadNext test
    [     1.223] I: =============================
    [     1.223] I: bool NotepadNextApplication::init()
    [     1.241] I: void NotepadNextApplication::loadTranslation(QLocale)
    [     1.241] I: en_US translation not found for Notepad Next
    [     1.241] I: en_US translation not found for Qt components
    [     1.241] I: LuaState::LuaState()
    [     1.276] I: MainWindow::MainWindow(NotepadNextApplication*)
    [     1.312] I: setupUi Completed
    [     1.352] I: void MainWindow::setupLanguageMenu()
    [     1.375] I: void MainWindow::restoreSettings()
    [     1.375] I: void NotepadNextApplication::openFiles(const QStringList&)
    [     1.375] I: void MainWindow::openFileList(const QStringList&)
    [     1.375] I: test
    [     8.033] I: Trying to create test
    [     8.033] D: Read 0 bytes
    [     8.033] D: BOM mark not found, using uchardet
    [     8.033] D: uchardet detected encoding as: ''
    [     8.033] D: Using codec: ''
    [     8.033] I: test last modified Mon Nov 21 21:25:50 2022
    [     8.033] I: void EditorManager::setupEditor(ScintillaNext*)
    [     8.037] D: EditorConfig settings for: "/home/deck/.local/bin/test"
    [     8.037] I: void MainWindow::addEditor(ScintillaNext*)
    [     8.037] I: void MainWindow::detectLanguage(ScintillaNext*)
    [     8.037] I: QString NotepadNextApplication::detectLanguageFromExtension(const QString&) const
    [     8.037] I: void MainWindow::setLanguage(ScintillaNext*, const QString&)
    [     8.037] I: Language Name: Text
    [     8.038] I: void DockedEditor::addEditor(ScintillaNext*)
    [     8.052] I: void MainWindow::activateEditor(ScintillaNext*)
    [     8.052] I: bool MainWindow::checkFileForModification(ScintillaNext*)
    [     8.053] I: test last modified Mon Nov 21 21:25:50 2022
    [     8.053] I: void MainWindow::updateGui(ScintillaNext*)
    [     8.053] I: void MainWindow::updateFileStatusBasedUi(ScintillaNext*)
    [     8.053] I: void MainWindow::updateSaveStatusBasedUi(ScintillaNext*)
    [     8.053] I: void MainWindow::updateEOLBasedUi(ScintillaNext*)
    [     8.053] I: void MainWindow::updateLanguageBasedUi(ScintillaNext*)
    (deck@steamdeck bin)$ flatpak run com.github.dail8859.NotepadNext test2 &
    [2] 15511
    [     1.182] W: Qt: Session management error: Could not open network socket
    [    15.739] I: void MainWindow::bringWindowToForeground()
    [     1.222] I: =============================
    [     1.222] I: Notepad Next v0.5.4 (Flatpak)
    [     1.222] I: Build Date/Time: Sep 11 2022 17:51:29
    [     1.222] I: Qt: 5.15.7
    [     1.222] I: OS: KDE Flatpak runtime
    [     1.222] I: Locale: en_US
    [     1.222] I: CPU: x86_64
    [     1.222] I: File Path: /app/bin/NotepadNext
    [     1.222] I: Arguments: NotepadNext test2
    [     1.222] I: =============================
    [     1.223] I: Primary instance already running. PID: 2
    [    15.741] I: void NotepadNextApplication::openFiles(const QStringList&)
    [    15.741] I: void MainWindow::openFileList(const QStringList&)
    [    15.741] I: test2
    [     1.233] I: Secondary instance closing...
    [    18.299] I: Trying to create test2
    [    18.300] D: Read 0 bytes
    [    18.300] D: BOM mark not found, using uchardet
    [    18.300] D: uchardet detected encoding as: ''
    [    18.300] D: Using codec: ''
    [    18.301] I: test2 last modified Mon Nov 21 21:26:00 2022
    [    18.301] I: void EditorManager::setupEditor(ScintillaNext*)
    [    18.302] D: EditorConfig settings for: "/home/deck/.local/bin/test2"
    [    18.302] I: void MainWindow::addEditor(ScintillaNext*)
    [    18.302] I: void MainWindow::detectLanguage(ScintillaNext*)
    [    18.303] I: QString NotepadNextApplication::detectLanguageFromExtension(const QString&) const
    [    18.303] I: void MainWindow::setLanguage(ScintillaNext*, const QString&)
    [    18.303] I: Language Name: Text
    [    18.303] I: void DockedEditor::addEditor(ScintillaNext*)
    [    18.311] I: void MainWindow::activateEditor(ScintillaNext*)
    [    18.312] I: bool MainWindow::checkFileForModification(ScintillaNext*)
    [    18.313] I: test2 last modified Mon Nov 21 21:26:00 2022
    [    18.313] I: void MainWindow::updateGui(ScintillaNext*)
    [    18.313] I: void MainWindow::updateFileStatusBasedUi(ScintillaNext*)
    [    18.314] I: void MainWindow::updateSaveStatusBasedUi(ScintillaNext*)
    [    18.314] I: void MainWindow::updateEOLBasedUi(ScintillaNext*)
    [    18.314] I: void MainWindow::updateLanguageBasedUi(ScintillaNext*)

**Comment by dail8859** [comment] 2022-11-21 21:01
@HeWhoThreadsLightly Thanks for the detailed report!

> [     1.185] W: Qt: Session management error: Could not open network socket

This definitely seems related. Notepad Next uses https://github.com/itay-grudev/SingleApplication to handle the single instance mode. Which I believe uses local sockets. Is there any type of restrictions for steamos that would prevent sockets being opened?

> [     1.223] I: Notepad Next v0.5.4 (Flatpak)

@zocker-160 I was going to suggest to @HeWhoThreadsLightly to update to v0.5.6 (or if the update wasn't fully published yet to at least update to v0.5.5), but according to https://flathub.org/apps/details/com.github.dail8859.NotepadNext it still shows **v0.5.4** as the latest release. Am I missing something here?

**Comment by HeWhoThreadsLightly** [comment] 2022-11-21 21:31
I don't know if steamos has any restrictions on opening sockets, most things works fine like KDE connect that _i think_ uses sockets at least it does something on the local network. I can test stuff if you have ideas.

I am on the latest version acording to discover:

    (deck@steamdeck ~)$ flatpak list | grep Note
    Notepad Next    com.github.dail8859.NotepadNext v0.5.4  stable  flathub system

**Comment by zocker-160** [comment] 2022-11-21 21:56
@dail8859 
> @zocker-160 I was going to suggest to @HeWhoThreadsLightly to update to v0.5.6 (or if the update wasn't fully published yet to at least update to v0.5.5), but according to [https://flathub.org/apps/details](https://flathub.org/apps/details/com.github.dail8859.NotepadNext)

The v0.5.6 update is not published yet (I have just triggered the force publish pipeline, so it should be available soon-ish). I will then try to reproduce that bug.
I think that this issue might be related to xdg-portal (which QT uses in the backend) and that is currently completely broken on SteamOS. (it should be fixed in preview, see https://store.steampowered.com/news/app/1675200/view/3383920059429575957)

>  Fixed issue with opening file managers if the gamescope session has been restarted

**Comment by dail8859** [comment] 2022-11-21 22:02
> The v0.5.6 update is not published yet

Not a big deal for v0.5.6 but I at least expect v0.5.5 to be available since it was published 2022-09-24

**Comment by zocker-160** [comment] 2022-11-21 22:08
I sadly cannot reproduce this issue on the latest version. The file gets created when I select "Yes" on the dialog and I can use NN normally.

Is it possible, that you are trying to create / access files from the SD card on your Steam Deck @HeWhoThreadsLightly ?

**Comment by zocker-160** [comment] 2022-11-21 22:23
@dail8859 issue seems unrelated to SingleApplication, because AFAIK (just like QSingleApplication) it uses a unix socket in the tmp folder and that one does work in the Flatpak just fine:

```bash
$ flatpak run com.github.dail8859.NotepadNext test2
[     1.082] W: Qt: Session management error: Could not open network socket
[     1.116] I: =============================
[     1.116] I: Notepad Next v0.5.6 (Flatpak)
[     1.116] I: Build Date/Time: Nov 21 2022 18:58:03
[     1.116] I: Qt: 5.15.7
[     1.116] I: OS: KDE Flatpak runtime
[     1.116] I: Locale: de_DE
[     1.116] I: CPU: x86_64
[     1.116] I: File Path: /app/bin/NotepadNext
[     1.116] I: Arguments: NotepadNext test2
[     1.116] I: =============================
[     1.116] I: Primary instance already running. PID: 2
[     1.130] I: Secondary instance closing...
```

### A few further observations:
Creating `test1` and `test2` files and then opening both in NN using command line works as expected, a new tab to the already running instance is added.

log:
```
[    25.823] I: void MainWindow::setLanguage(ScintillaNext*, const QString&)
[    25.823] I: Language Name: Text
[    25.823] I: void DockedEditor::addEditor(ScintillaNext*)
[    25.825] I: void MainWindow::activateEditor(ScintillaNext*)
[    25.825] I: bool MainWindow::checkFileForModification(ScintillaNext*)
[    25.826] I: test2 last modified Mo. Nov. 21 23:18:37 2022
[    25.826] I: void MainWindow::updateGui(ScintillaNext*)
[    25.826] I: void MainWindow::updateFileStatusBasedUi(ScintillaNext*)
[    25.826] I: void MainWindow::updateSaveStatusBasedUi(ScintillaNext*)
[    25.826] I: void MainWindow::updateEOLBasedUi(ScintillaNext*)
[    25.826] I: void MainWindow::updateLanguageBasedUi(ScintillaNext*)
[    26.036] I: Scintilla::Internal::RegexSearchBase* Scintilla::Internal::CreateRegexSearch(CharClassify*)
```
But (as reported by OP) when trying to open the secondary instance while the file does not exist, it always crashes after the `File does not exist, do you want to create it.` dialog.

**Comment by zocker-160** [comment] 2022-11-21 22:25
Issue happens with the Appimage as well, this problem is not related to packaging or Flatpak.

**Comment by dail8859** [comment] 2022-11-21 22:42
> Issue happens with the Appimage as well, this problem is not related to packaging or Flatpak.

Awesome! Guess my initial assumption was incorrect. This starts to narrow down the issue quite a bit now.

**Comment by zocker-160** [comment] 2022-11-22 00:50
Alright so I did a bit of digging, because I got curious what is going on and it seems that something very funky is going on.

The segfault happens here:
https://github.com/dail8859/NotepadNext/blob/065e26caa254a029babbc9a2452d9b9ca17eb177/src/NotepadNext/dialogs/MainWindow.cpp#L667

The weird thing is, that it seems to have something to do with the QMessagebox, because when I remove it and hard code an answer, it all works without crash.

doing something stupid like this, does "fix" the segfault
```cpp
        if (editor == Q_NULLPTR) {
            qInfo("EDITOR nullptr");
            QFileInfo fileInfo(filePath);

            if (!fileInfo.isFile()) {
#if defined(Q_OS_LINUX)
                if (true) {
#else
                auto reply = QMessageBox::question(this, tr("Create File"), tr("<b>%1</b> does not exist. Do you want to create it?").arg(filePath));

                if (reply == QMessageBox::Yes) {
#endif
                    editor = app->getEditorManager()->createEditorFromFile(filePath, true);
                }
                else {
                    // Make sure it is not still in the recent files list still.
                    // Normally when a file is opened it is removed from the file list,
                    // but if a user doesn't want to create the file, remove it explicitly.
                    qInfo("app->getRecentFilesListManager()->removeFile(filePath);");
                    app->getRecentFilesListManager()->removeFile(filePath);
                    qInfo("continue");
                    continue;
                    //break;
                }
            }
            else {
                editor = app->getEditorManager()->createEditorFromFile(filePath);
            }
        }
```

Maybe you have an idea what is going on here xD

**Comment by dail8859** [comment] 2022-11-22 02:47
> it seems to have something to do with the QMessagebox

I remember running into something similar in the past on windows. It isn't `QMessageBox` itself, but since it was being shown at an unexpected time, other parts of the code were referencing things that weren't instantiated yet. Not related to this issue, but might end up being something similar.

---

I need to start giving Qt a bit more credit instead of immediately blaming it when something looks odd. Looking back through the log definitely shows my assumption was **completely wrong**. My bad. The secondary instance was indeed detected correctly and sent the information over to the main instance. I haven't been able to reproduce this on Windows. When I get some free time I'll get my Linux VM booted back up and debug it there.

**Comment by HeWhoThreadsLightly** [comment] 2022-11-22 21:53
Made a temporary workaround that i added to my .bashrc, might keep it to skip the create file dialog later.

    #Notepad next wraper 
    note() {
    	#workaround for bug with mising files by creating them before opening notepad next
    	for file in "$@"; do
    		#checking if file exist to avoid unnecessarily modififying timestams
    		if [ ! -f $file ]; then 
    			echo $file
    			touch $file
    		fi
    	done
    	#open Notepad next and free it from bash's lifetime
    	(flatpak run com.github.dail8859.NotepadNext $@ & disown; ) 2> /dev/null
    }

**Comment by dail8859** [comment] 2022-11-23 03:24
After **a lot** of debugging and trial and error, I found a way to keep it from crashing, but I'm not sure if this is the _right_ solution, or just a solution that makes it not crash.

If I change this connection to a `Qt::QueuedConnection` everything works as expected. This is what handles processing the data sent from the secondary instance.

https://github.com/dail8859/NotepadNext/blob/065e26caa254a029babbc9a2452d9b9ca17eb177/src/NotepadNext/NotepadNextApplication.cpp#L185-L197

**Closed** 2022-11-23 20:36 UTC
Labels: linux

**Comment by dail8859** [comment] 2022-11-23 20:37
I committed the changes. I can't guarantee this fixes the root issue, but at least in the short-term gives _better_ behavior. Windows seems unaffected by either connection type.
