### ISSUE TITLE
Constantly NotepadNext crashes Ubuntu 22.04.3 LTS

### ISSUE THREAD

**Issue by JuanRodenas** [dail8859/NotepadNext#490] opened 2023-12-12 17:37 UTC
Hello,

On Ubuntu 22.04.3 LTS I get the following in the log.
```
[  2725.090] I: QFileDevice::FileError ScintillaNext::save()
[  2725.090] I: QFileDevice::FileError writeToDisk(const QByteArray&, const QString&)
[  3854.429] I: void MainWindow::updateGui(ScintillaNext*)
[  3854.430] I: void MainWindow::updateFileStatusBasedUi(ScintillaNext*)
[  3854.430] I: void MainWindow::updateSaveStatusBasedUi(ScintillaNext*)
[  3854.430] I: void MainWindow::updateEOLBasedUi(ScintillaNext*)
[  3854.430] I: void MainWindow::updateLanguageBasedUi(ScintillaNext*)
[  3862.427] I: void MainWindow::updateSaveStatusBasedUi(ScintillaNext*)
```

Constantly NotepadNext crashes and the window pops up:
![photo_2023-12-12_18-29-34](https://github.com/dail8859/NotepadNext/assets/95724863/fb125b1d-c6a8-4ef7-8886-96f5ae7275ee)

**Comment by dail8859** [comment] 2023-12-12 17:42
Can you paste the first 10 lines or so of your log? That will show some useful application and system information.

**Comment by JuanRodenas** [comment] 2023-12-13 09:47
Hello, yes, here are the lines.
```
[     0.524] I: =============================
[     0.524] I: Notepad Next v0.6.4 (AppImage)
[     0.524] I: Build Date/Time: Oct 18 2023 16:54:18
[     0.524] I: Qt: 6.5.3
[     0.524] I: OS: Ubuntu 22.04.3 LTS
[     0.524] I: Locale: es_ES
[     0.524] I: CPU: x86_64
[     0.524] I: File Path: /tmp/.mount_NotepaWUutd0/usr/bin/NotepadNext
[     0.524] I: Arguments: /tmp/.mount_NotepaWUutd0/AppRun.wrapped /home/XXXX/Documentos/XXXX.sh
[     0.524] I: =============================
```

**Comment by dail8859** [comment] 2023-12-13 12:46
Nothing looks odd. From the original log it looks like the file was saved, and then some time later at the 3854 second mark something caused the application to refresh the UI and then crash.

Are you able to reproduce the issue at all? Or any idea what action triggers the crash?

**Comment by JuanRodenas** [comment] 2023-12-13 16:06
Hello, I have tried to reproduce the error. And it happens when saving and in large files.

**Comment by dail8859** [comment] 2023-12-13 16:48
> And it happens when saving and in large files.

Does file location matter? Is it related to file permissions? Any details you can provide to help narrow down the issue would be great.

"Large" is a relative term...how big are the files? 2MB? 20MB? 200MB? 2G? Etc?

**Comment by JuanRodenas** [comment] 2023-12-13 18:39
Hello,
I have been able to reproduce the error. Big I mean lines of content, but in the end I was able to reproduce it with a .txt of a couple of lines and another called prueba.sh the same. I attach a file with the debug and the screenshots of the file so you can see the permissions.

![Captura desde 2023-12-13 19-35-07](https://github.com/dail8859/NotepadNext/assets/95724863/5fc36b71-405e-4532-a82a-b32dc6954bd7)
![Captura desde 2023-12-13 19-35-40](https://github.com/dail8859/NotepadNext/assets/95724863/be55cbbd-3876-4743-94cb-385172776e09)

And, ,txt file:
[error.txt](https://github.com/dail8859/NotepadNext/files/13664392/error.txt)

**Comment by dail8859** [comment] 2023-12-13 18:45
I can't read Spanish(?) at all. Can you run an `ls` command on the file to show permissions?

**Comment by JuanRodenas** [comment] 2023-12-13 18:50
Yes, it is in Spanish.
Any information you need, ask me and I will translate it for you.

```js
-rw-rw-r-- 1 juan juan 2079 dec 13 19:46 prueba.sh
-rw-rw-r-- 1 juan juan 1495 dec 13 19:32 data icons.txt
```

**Comment by dail8859** [comment] 2023-12-13 18:57
> `-rw-rw-r-- 1 juan juan 2079 dec 13 19:46 prueba.sh`

Odd...it seems to have write permissions. I don't have a Linux VM available so I'm not sure what else to check off the top of my head.

**Comment by JuanRodenas** [comment] 2023-12-13 19:08
If you have any data, questions or suggestions, please contact me.
Even if you want deeper information, you can request me the Discord by email and we can see it in more detail.
I look forward to helping you.

**Comment by inkydragon** [comment] 2023-12-17 20:52
I'm trying to reproduce this issue on Windows in WSL2 (Ubuntu 22.04.3 LTS).
If we can't reproduce the problem, then it's also hard to solve it

I have some questions. @JuanRodenas 

- Can you reproduce the problem by following these steps?
- Does your text file contain Spanish characters? Or only ASCII characters?
- Is there a fixed amount of time to wait before crashing? Is there a minimum wait time of about 3800s, or is the crash time uncertain?
- Can a crash be triggered by just opening the file and doing nothing?
- Can you give me a text file that could trigger the problem?
- If you run NotepadNext with `LC_ALL=en_US.UTF-8`, does the problem still exist?

The core of the above question is whether it is possible to give a fixed set of actions that can reproduce the problem.
Of course, since WSL2 is actually a virtual machine of some kind, perhaps this problem only exists on Ubuntu systems with physical machines.


My reproduce steps:
```
python3 -c 'print(", ".join([ str(i) for i in range(1,10**5) ]))' > prueba.sh
ll -h prueba.sh
sudo locale-gen es_ES.UTF-8
LC_ALL=es_ES.UTF-8 ./NotepadNext-v0.6.4-x86_64.AppImage ./prueba.sh
```

<details>
<summary>long log - NO crash</summary>

```
cyhan@A309-Y9000P:~$ LC_ALL=es_ES.UTF-8 ./NotepadNext-v0.6.4-x86_64.AppImage ./prueba.sh
[     0.035] W: Could not find the Qt platform plugin "wayland" in ""
[     0.100] I: =============================
[     0.100] I: Notepad Next v0.6.4 (AppImage)
[     0.100] I: Build Date/Time: Oct 18 2023 16:54:18
[     0.100] I: Qt: 6.5.3
[     0.100] I: OS: Ubuntu 22.04.3 LTS
[     0.100] I: Locale: es_ES
[     0.100] I: CPU: x86_64
[     0.100] I: File Path: /tmp/.mount_NotepaXOwZNt/usr/bin/NotepadNext
[     0.100] I: Arguments: /tmp/.mount_NotepaXOwZNt/AppRun.wrapped ./prueba.sh
[     0.100] I: =============================
[     0.100] I: bool NotepadNextApplication::init()
[     0.114] I: void NotepadNextApplication::loadTranslation(QLocale)
[     0.114] I: es_ES translation not found for Notepad Next
[     0.114] I: es_ES translation not found for Qt components
[     0.114] I: LuaState::LuaState()
[     0.130] I: MacroManager::MacroManager(QObject*)
[     0.130] I: void MacroManager::loadSettings()
[     0.130] I: MainWindow::MainWindow(NotepadNextApplication*)
[     0.148] I: setupUi Completed
[     0.189] I: FileListDock::FileListDock(MainWindow*)
[     0.189] I: void MainWindow::setupLanguageMenu()
[     0.194] I: void MainWindow::restoreSettings()
[     0.195] I: void NotepadNextApplication::openFiles(const QStringList&)
[     0.195] I: void MainWindow::openFileList(const QStringList&)
[     0.195] I: ./prueba.sh
[     0.196] D: Read 688886 bytes
[     0.196] D: BOM mark not found, using uchardet
[     0.196] D: uchardet detected encoding as: 'ASCII'
[     0.196] D: Using codec: 'US-ASCII'
[     0.196] I: prueba.sh last modified Sun Dec 17 13:25:41 2023
[     0.197] I: void EditorManager::setupEditor(ScintillaNext*)
[     0.199] D: EditorConfig settings for: "/home/cyhan/prueba.sh"
[     0.199] I: void MainWindow::addEditor(ScintillaNext*)
[     0.199] I: void MainWindow::detectLanguage(ScintillaNext*)
[     0.199] I: QString NotepadNextApplication::detectLanguage(ScintillaNext*) const
[     0.199] I: QString NotepadNextApplication::detectLanguageFromExtension(const QString&) const
[     0.199] I: void MainWindow::setLanguage(ScintillaNext*, const QString&)
[     0.199] I: Language Name: bash
[     0.202] I: void DockedEditor::addEditor(ScintillaNext*)
[     0.213] I: void MainWindow::activateEditor(ScintillaNext*)
[     0.213] I: bool MainWindow::checkFileForModification(ScintillaNext*)
[     0.213] I: prueba.sh last modified Sun Dec 17 13:25:41 2023
[     0.213] I: void MainWindow::updateGui(ScintillaNext*)
[     0.213] I: void MainWindow::updateFileStatusBasedUi(ScintillaNext*)
[     0.213] I: void MainWindow::updateSaveStatusBasedUi(ScintillaNext*)
[     0.213] I: void MainWindow::updateEOLBasedUi(ScintillaNext*)
[     0.213] I: void MainWindow::updateLanguageBasedUi(ScintillaNext*)
[     0.681] I: Scintilla::Internal::RegexSearchBase* Scintilla::Internal::CreateRegexSearch(Scintilla::Internal::CharClassify*)
[    11.932] I: void MainWindow::updateSaveStatusBasedUi(ScintillaNext*)
[    15.923] I: QFileDevice::FileError ScintillaNext::save()
[    15.923] I: QFileDevice::FileError writeToDisk(const QByteArray&, const QString&)
[    15.924] I: prueba.sh last modified Sun Dec 17 13:29:56 2023
[    15.924] I: void MainWindow::updateSaveStatusBasedUi(ScintillaNext*)
[    15.924] I: void MainWindow::updateSaveStatusBasedUi(ScintillaNext*)
[    17.778] I: void MainWindow::updateSaveStatusBasedUi(ScintillaNext*)
[    21.608] I: QFileDevice::FileError ScintillaNext::save()
[    21.608] I: QFileDevice::FileError writeToDisk(const QByteArray&, const QString&)
[    21.619] I: prueba.sh last modified Sun Dec 17 13:30:01 2023
[    21.619] I: void MainWindow::updateSaveStatusBasedUi(ScintillaNext*)
[    21.619] I: void MainWindow::updateSaveStatusBasedUi(ScintillaNext*)
[    22.938] I: void MainWindow::updateSaveStatusBasedUi(ScintillaNext*)
[    24.616] I: QFileDevice::FileError ScintillaNext::save()
[    24.616] I: QFileDevice::FileError writeToDisk(const QByteArray&, const QString&)
[    24.617] I: prueba.sh last modified Sun Dec 17 13:30:04 2023
[    24.617] I: void MainWindow::updateSaveStatusBasedUi(ScintillaNext*)
[    24.617] I: void MainWindow::updateSaveStatusBasedUi(ScintillaNext*)
[   257.921] I: void MainWindow::updateSaveStatusBasedUi(ScintillaNext*)
[   486.371] I: QFileDevice::FileError ScintillaNext::save()
[   486.372] I: QFileDevice::FileError writeToDisk(const QByteArray&, const QString&)
[   486.372] I: prueba.sh last modified Sun Dec 17 13:37:46 2023
[   486.372] I: void MainWindow::updateSaveStatusBasedUi(ScintillaNext*)
[   486.372] I: void MainWindow::updateSaveStatusBasedUi(ScintillaNext*)
[  1194.997] I: void MainWindow::updateSaveStatusBasedUi(ScintillaNext*)
[  1578.254] I: QFileDevice::FileError ScintillaNext::save()
[  1578.254] I: QFileDevice::FileError writeToDisk(const QByteArray&, const QString&)
[  1578.255] I: prueba.sh last modified Sun Dec 17 13:55:58 2023
[  1578.255] I: void MainWindow::updateSaveStatusBasedUi(ScintillaNext*)
[  1578.256] I: void MainWindow::updateSaveStatusBasedUi(ScintillaNext*)
[  2335.830] I: void MainWindow::updateSaveStatusBasedUi(ScintillaNext*)
[  2567.883] I: QFileDevice::FileError ScintillaNext::save()
[  2567.883] I: QFileDevice::FileError writeToDisk(const QByteArray&, const QString&)
[  2567.885] I: prueba.sh last modified Sun Dec 17 14:12:28 2023
[  2567.885] I: void MainWindow::updateSaveStatusBasedUi(ScintillaNext*)
[  2567.886] I: void MainWindow::updateSaveStatusBasedUi(ScintillaNext*)
[  2753.996] I: void MainWindow::updateSaveStatusBasedUi(ScintillaNext*)
[  2754.215] I: QFileDevice::FileError ScintillaNext::save()
[  2754.215] I: QFileDevice::FileError writeToDisk(const QByteArray&, const QString&)
[  2754.216] I: prueba.sh last modified Sun Dec 17 14:15:34 2023
[  2754.216] I: void MainWindow::updateSaveStatusBasedUi(ScintillaNext*)
[  2754.216] I: void MainWindow::updateSaveStatusBasedUi(ScintillaNext*)
[  2755.899] I: void MainWindow::updateSaveStatusBasedUi(ScintillaNext*)
[  2756.339] I: QFileDevice::FileError ScintillaNext::save()
[  2756.340] I: QFileDevice::FileError writeToDisk(const QByteArray&, const QString&)
[  2756.340] I: prueba.sh last modified Sun Dec 17 14:15:36 2023
[  2756.340] I: void MainWindow::updateSaveStatusBasedUi(ScintillaNext*)
[  2756.341] I: void MainWindow::updateSaveStatusBasedUi(ScintillaNext*)
[  2821.545] I: void MainWindow::updateSaveStatusBasedUi(ScintillaNext*)
[  2825.438] I: QFileDevice::FileError ScintillaNext::save()
[  2825.438] I: QFileDevice::FileError writeToDisk(const QByteArray&, const QString&)
[  2825.439] I: prueba.sh last modified Sun Dec 17 14:16:45 2023
[  2825.439] I: void MainWindow::updateSaveStatusBasedUi(ScintillaNext*)
[  2825.439] I: void MainWindow::updateSaveStatusBasedUi(ScintillaNext*)
[  2910.974] I: void MainWindow::updateSaveStatusBasedUi(ScintillaNext*)
[  2911.398] I: QFileDevice::FileError ScintillaNext::save()
[  2911.398] I: QFileDevice::FileError writeToDisk(const QByteArray&, const QString&)
[  2911.398] I: prueba.sh last modified Sun Dec 17 14:18:11 2023
[  2911.398] I: void MainWindow::updateSaveStatusBasedUi(ScintillaNext*)
[  2911.398] I: void MainWindow::updateSaveStatusBasedUi(ScintillaNext*)
[  3406.712] I: void MainWindow::updateSaveStatusBasedUi(ScintillaNext*)
[  3406.929] I: QFileDevice::FileError ScintillaNext::save()
[  3406.929] I: QFileDevice::FileError writeToDisk(const QByteArray&, const QString&)
[  3406.930] I: prueba.sh last modified Sun Dec 17 14:26:27 2023
[  3406.930] I: void MainWindow::updateSaveStatusBasedUi(ScintillaNext*)
[  3406.930] I: void MainWindow::updateSaveStatusBasedUi(ScintillaNext*)
[  3415.323] I: void MainWindow::updateSaveStatusBasedUi(ScintillaNext*)
[  3415.972] I: QFileDevice::FileError ScintillaNext::save()
[  3415.973] I: QFileDevice::FileError writeToDisk(const QByteArray&, const QString&)
[  3415.973] I: prueba.sh last modified Sun Dec 17 14:26:36 2023
[  3415.973] I: void MainWindow::updateSaveStatusBasedUi(ScintillaNext*)
[  3415.974] I: void MainWindow::updateSaveStatusBasedUi(ScintillaNext*)
[  3418.656] I: void MainWindow::updateSaveStatusBasedUi(ScintillaNext*)
[  3419.691] I: void MainWindow::updateSaveStatusBasedUi(ScintillaNext*)
[  3421.987] I: void MainWindow::updateSaveStatusBasedUi(ScintillaNext*)
[  3423.929] I: QFileDevice::FileError ScintillaNext::save()
[  3423.929] I: QFileDevice::FileError writeToDisk(const QByteArray&, const QString&)
[  3423.930] I: prueba.sh last modified Sun Dec 17 14:26:44 2023
[  3423.930] I: void MainWindow::updateSaveStatusBasedUi(ScintillaNext*)
[  3423.931] I: void MainWindow::updateSaveStatusBasedUi(ScintillaNext*)
[  4924.493] I: void MainWindow::updateSaveStatusBasedUi(ScintillaNext*)
[  4929.074] I: QFileDevice::FileError ScintillaNext::save()
[  4929.075] I: QFileDevice::FileError writeToDisk(const QByteArray&, const QString&)
[  4929.076] I: prueba.sh last modified Sun Dec 17 14:51:49 2023
[  4929.076] I: void MainWindow::updateSaveStatusBasedUi(ScintillaNext*)
[  4929.076] I: void MainWindow::updateSaveStatusBasedUi(ScintillaNext*)
[  4930.098] I: void MainWindow::updateSaveStatusBasedUi(ScintillaNext*)
[  4934.589] I: QFileDevice::FileError ScintillaNext::save()
[  4934.589] I: QFileDevice::FileError writeToDisk(const QByteArray&, const QString&)
[  4934.600] I: prueba.sh last modified Sun Dec 17 14:51:54 2023
[  4934.600] I: void MainWindow::updateSaveStatusBasedUi(ScintillaNext*)
[  4934.600] I: void MainWindow::updateSaveStatusBasedUi(ScintillaNext*)
[  4940.486] I: void MainWindow::saveSettings() const
[  4940.499] I: void RecentFilesListManager::addFile(const QString&)
[  4940.500] I: void SessionManager::saveSession(MainWindow*)
[  4940.512] I: void MacroManager::saveSettings() const
cyhan@A309-Y9000P:~$
```

</details>

**Comment by dail8859** [comment] 2023-12-27 20:35
Closing as there is not enough details to reproduce the issue.

**Closed by dail8859** 2023-12-27 20:34 UTC
Labels: linux
