### ISSUE TITLE
annoying grid visible in document

### ISSUE THREAD

**Issue by sven-cnrd** [dail8859/NotepadNext#616] opened 2024-08-06 08:00 UTC
### Operating System and Version

Kubuntu 22.04

### Distribution

flathub

### Description

There is a grid running through the document area. I suspect the reason is that I am using Kubuntu 22.04 with Global Scale set to 125% in the Display Settings. If I disable the Global Scale (set to 100%) the issue disappears. 
Zooming changes the grid slightly. Some lines disappear, other appear additionally. But there is no Zoom level without the annoying lines.

![image](https://github.com/user-attachments/assets/d257a19d-ef7a-4dc1-8737-6188613aadef)

### Steps to Reproduce

1. install latest flatpak package on Kubuntu 22.04
2. Set Global scale to 125%, reboot.
3. open any document with Notepad Next

### Additional Details

![image](https://github.com/user-attachments/assets/db44b80a-7912-4485-80c9-939b86391189)
![image](https://github.com/user-attachments/assets/078412b1-7f71-4363-ad7a-8ad9df701577)

**Comment by dail8859** [comment] 2024-08-06 15:19
Duplicate of #344

A similar issue appeared on Windows. We determined it is either a Qt bug or Scintilla (which is what does the lower-level text rendering). There did not seem to be any way for Notepad Next to fix it unfortunately.

**Closed by dail8859** 2024-08-06 15:19 UTC
Labels: scintilla
