### ISSUE TITLE
can not edit hosts file

### ISSUE THREAD

**Issue by timnick-snow** [dail8859/NotepadNext#312] opened 2023-01-31 06:44 UTC
![image](https://user-images.githubusercontent.com/33312542/215686253-88d8803c-77e8-43b8-994f-fbccbfddafed.png)

**Comment by ZachBacon** [comment] 2023-01-31 07:20
Did you run notepad-next with administrative privileges? Because that's the only way a hosts file can be saved.

**Comment by timnick-snow** [comment] 2023-01-31 08:45
I usually use right click and select edit with Notepad Next.  When I use notepad++ to edit, it prompts me to enable administrator privileges, and then I can easily edit the hosts file.

**Comment by ZachBacon** [comment] 2023-01-31 14:49
Right click on notepad next, run as administrator and edit that way

**Comment by dail8859** [comment] 2023-01-31 15:48
Agreed the root cause is a permissions issue. I think at a minimum a better error message should be provided. Not sure what all it takes to relaunch itself in admin mode.

**Comment by timnick-snow** [comment] 2023-02-01 00:41
> Right click on notepad next, run as administrator and edit that way

I prefer to find the target file first, then right click to edit.

**Comment by dail8859** [comment] 2023-02-01 03:19
> I prefer to find the target file first, then right click to edit.

Ultimately it comes down to the OS implementing reasonable security features. If you aren't concerned about security, you can bypass this in a number of different ways. That doesn't mean Notepad Next can't make it a bit easier for the user though.

So, I think it needs taken in steps with varying degrees of usefulness vs difficulty.

1. Implement more robust error handling along with useful dialog messages (done, see screenshot)
1. Present the user with other options e.g. save the file elsewhere
1. If a file is opened and the OS reports it as not being writable, create a _very non-intrusive_ way to let the user know. Not sure how best to do that yet.
1. Elevate privileges at runtime. From the looks of it, Notepad++ saves the file elsewhere temporarily, restarts itself with admin privileges, reloads the file, then the user can save it. This definitely doesn't seem easy to do cross-platform and requiring the whole application to run elevated to write a file seems a bit overkill, but that's just my opinion.


![image](https://user-images.githubusercontent.com/3694843/215932233-b3f2a6d6-7389-4390-ac33-fcda4708acf0.png)

**Comment by dail8859** [comment] 2023-02-04 20:16
Closing for now as I think an accurate error message is appropriate to let the user know what went wrong and let them decide how to handle it. This may be improved upon on the future.

**Closed by dail8859** 2023-02-04 20:16 UTC
