### ISSUE TITLE
Dark lines at end of and under text lines

### ISSUE THREAD

**Issue by jhob101** [dail8859/NotepadNext#620] opened 2024-08-10 14:13 UTC
### Operating System and Version

ZorinOS 17.1 (Ubuntu 22.04)

### Distribution

flathub

### Description

Dark lines show at end of and under lines.  Looks messy and I don't think is intended.

I've toggled all settings I could find but nothing has made a difference.
![2024-08-10_15-09](https://github.com/user-attachments/assets/c026cc1f-a3e7-49ef-9c01-e89cb990d424)

### Steps to Reproduce

1. Start application
2. Type something

### Additional Details

e.g. screenshots, logs, etc

**Comment by dail8859** [comment] 2024-08-10 17:20
Duplicate of #344 and #616

A similar issue appeared on Windows and Lunx. We determined it is either a Qt bug or Scintilla (which is what does the lower-level text rendering). There did not seem to be any way for Notepad Next to fix it unfortunately.

**Closed** 2024-08-10 17:21 UTC
Labels: scintilla
