### ISSUE TITLE
MacOS Dark Mode

### ISSUE THREAD

**Issue by cropester** [dail8859/NotepadNext#553] opened 2024-05-06 16:53 UTC
### Description

It would be great if there was a way to activate dark mode under MacOS. Unfortunately, I can't find the option at the moment.

### Describe the solution you'd like

The selection in the settings for dark mode, light mode or automatic.

**Comment by dail8859** [comment] 2024-05-06 19:08
Dark mode is not currently supported. There was a bit of work on it but nothing release worthy yet. Also newer versions of Qt have better dark mode support that needs to be evaluated. Closing as a duplicate of #407

**Closed by dail8859** 2024-05-06 19:08 UTC

**Comment by Neustradamus** [comment] 2026-05-05 08:22
Linked to:
- https://github.com/dail8859/NotepadNext/pull/1040
- https://github.com/dail8859/NotepadNext/issues/1029
- https://github.com/dail8859/NotepadNext/issues/930
- https://github.com/dail8859/NotepadNext/issues/720
- https://github.com/dail8859/NotepadNext/issues/553
- https://github.com/dail8859/NotepadNext/pull/411
- https://github.com/dail8859/NotepadNext/issues/407
- https://github.com/dail8859/NotepadNext/issues/288
- https://github.com/dail8859/NotepadNext/issues/171
- ...
