### ISSUE TITLE
A little bit slowly when open large file （>500MB). 

### ISSUE THREAD

**Issue by zhangfq-chemistry** [dail8859/NotepadNext#294] opened 2023-01-02 08:41 UTC
Would you like to optimize memory allocation? Thanks!

**Comment by dail8859** [comment] 2023-01-02 19:56
Closing as a duplicate of https://github.com/dail8859/NotepadNext/issues/284

For now I'd recommend not using the application for large files.

From your issue I'm not sure if it is a memory issue or it is slow.

Any specific details can be posted on that issue, such as example files, specific steps, or quantifiable comparisons to other applications such as Notepad++.

It is usually not very easy to track down things that are simply just "slow".

**Closed by dail8859** 2023-01-02 19:56 UTC
